### ISSUE TITLE
datasette-template-sql causes <function ...> in textarea

### ISSUE THREAD

**Issue by cldellow** [simonw/datasette-write#6]
If I install this plugin by itself and navigate to `/-/write`, I get an empty textarea for typing in SQL.

If I then add the [datasette-template-sql](https://github.com/simonw/datasette-template-sql) plugin, the textarea now has:

```
<function extra_template_vars.<locals>.execute_sql at 0x7fcaa98ea290>
```

Not a big deal, but it adds an extra step to delete it when running a query. (I also begin to wonder... is this from https://github.com/simonw/datasette-write/blob/main/datasette_write/templates/datasette_write.html#L13 ? Am I supposed to see some other SQL there some times, for example when I type in something with syntax errors?)

**Comment by simonw** [comment]
https://github.com/simonw/datasette-write/blob/aaa1dcb39188389f5610962f9f9b52c3d96dc302/datasette_write/__init__.py#L29

That's supposed to allow `?sql=` in the URL to pre-populate the form with a query ready to be executed, see also #7.

I hadn't run into an issue with plugins like `datasette-template-sql` interfering with the existing context for other features before! Definitely not a good thing.

**Comment by simonw** [comment]
![CleanShot 2024-02-27 at 10 52 50@2x](https://github.com/simonw/datasette-write/assets/9599/baa3cb66-32d8-481e-8615-315e452ad006)
